version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5000:5000"
    # Désactivation de la validation d'hôte pour accepter les requêtes provenant de l'alias 'mlflow'
    command: >
      mlflow ui 
      --host 0.0.0.0 
      --port 5000 
      --disable-host-validation

  app:
    build: .
    image: smartphones-ml-app
    container_name: ml_app_container
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlruns:/app/mlruns
